point_name = {
              'point_1': 'philhermagic',
              'point_2': 'country bear theatre',
              'point_3': 'pirates of carribian',
              'point_4': 'minnie''s style studio',
              'point_5': 'christmas stories',
              'point_6': 'reach for stars',
              'point_7': 'jamboree mickey',
              'point_8': 'magical music world',
              'point_9': 'pooh''s honey hunt'
              }

coordinate = {
              'point_1': (15, 14),
              'point_2': (1, 14),
              'point_3': (6, 3),
              'point_4': (26, 19),
              'point_5': (11, 7),
              'point_6': (11, 7),
              'point_7': (1, 7),
              'point_8': (31, 11),
              'point_9': (18, 16)
              }

distance_2point = {
                   ('point_1', 'point_2'): 14,
                   ('point_1', 'point_3'): 14.2,
                   ('point_1', 'point_4'): 12.08,
                   ('point_1', 'point_5'): 8.06,
                   ('point_1', 'point_6'): 8.06,
                   ('point_1', 'point_7'): 15.6,
                   ('point_1', 'point_8'): 16.2,
                   ('point_1', 'point_9'): 3.6,
                   ('point_2', 'point_3'): 12,
                   ('point_2', 'point_4'): 25.4,
                   ('point_2', 'point_5'): 12.2,
                   ('point_2', 'point_6'): 12.2,
                   ('point_2', 'point_7'): 7,
                   ('point_2', 'point_8'): 30.1,
                   ('point_2', 'point_9'): 17.1,
                   ('point_3', 'point_4'): 25.6,
                   ('point_3', 'point_5'): 6.4,
                   ('point_3', 'point_6'): 6.4,
                   ('point_3', 'point_7'): 6.4,
                   ('point_3', 'point_8'): 26.2,
                   ('point_3', 'point_9'): 17.6,
                   ('point_4', 'point_5'): 19.2,
                   ('point_4', 'point_6'): 19.2,
                   ('point_4', 'point_7'): 27.7,
                   ('point_4', 'point_8'): 9.4,
                   ('point_4', 'point_9'): 8.5,
                   ('point_5', 'point_6'): 0,
                   ('point_5', 'point_7'): 10,
                   ('point_5', 'point_8'): 20.3,
                   ('point_5', 'point_9'): 11.4,
                   ('point_6', 'point_7'): 10,
                   ('point_6', 'point_8'): 20.3,
                   ('point_6', 'point_9'): 11.4,
                   ('point_7', 'point_8'): 30.2,
                   ('point_7', 'point_9'): 19.2,
                   ('point_8', 'point_9'): 13.9,
                   }
